apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-depl
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z staging-postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
