apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Pingpong-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/artur-S213/gitopsDeploy
    path: kubernetes/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true